function [post,out] = BMC_plot(criterion,options)
if nargin<2
    options = struct();
end

options.DisplayWin = false;
[post,out] = VBA_groupBMC(-criterion'/2,options);

set(gcf,'Color',[1,1,1])

hold on

if ~isfield(options,'families')
    bar(squeeze(100*out.ep),...
        'FaceColor',.7*[1,1,1],...
        'EdgeColor','none')
    alpha(0.5)
    
    plot(squeeze(100*out.pxp),'-o',...
        'Color',.7*[1,1,1],...
        'MarkerFaceColor',.7*[1,1,1],...
        'MarkerEdgeColor',[1,1,1])
    
    errorbar(100*out.Ef,100*sqrt(out.Vf),'d',...
        'Color',.5*[1,1,1],...
        'MarkerFaceColor',.7*[1,1,1],...
        'MarkerEdgeColor',.5*[1,1,1],...
        'LineStyle','None')
    plot([-1,numel(out.Ef)+1],100*[1./numel(out.Ef),1./numel(out.Ef)],'r--');
    plot([-1,size(out.Ef,1)+1],100*[0.95,0.95],'b--')
    
    set(gca,'YLim', [0 100],...
        'XTick',1:numel(out.Ef),....%'XTickLabels',modelnames,...
        'XLim',[0 size(out.Ef,1)+1],...
        'FontName','Arial')
    xtickangle(90)
    hL = legend('Exceedence P.','Protected EP','Expected F.');
    hY = ylabel('probability');
    set([hY,hL],'FontName','Arial')
    set(hL,'Location','Best')
    legend boxoff
else
    
    bar(squeeze(100*out.families.ep),...
        'FaceColor',.7*[1,1,1],...
        'EdgeColor','none')
    alpha(0.5)
    
    errorbar(100*out.families.Ef,100*sqrt(out.families.Vf),'d',...
        'Color',.5*[1,1,1],...
        'MarkerFaceColor',.7*[1,1,1],...
        'MarkerEdgeColor',.5*[1,1,1],...
        'LineStyle','None')
    plot([-1,numel(out.families.Ef)+1],100*[1./numel(out.families.Ef),1./numel(out.families.Ef)],'r--');
    plot([-1,size(out.families.Ef,1)+1],100*[0.95,0.95],'b--')
    
    set(gca,'YLim', [0 100],...
        'XTick',1:numel(out.families.Ef),....%'XTickLabels',modelnames,...
        'XLim',[0 size(out.families.Ef,1)+1],...
        'FontName','Arial')
    xtickangle(90)
    hL = legend('Exceedence P.','Expected F.');
    hY = ylabel('probability');
    set([hY,hL],'FontName','Arial')
    set(hL,'Location','Best')
    legend boxoff
    
end