function latexCode = replaceWords(latexCode,oldName,newName)
%   Rename some user-defined strings in the Latex table
%   latex_code = replaceWords(latex_code,oldName,newName) is the new
%   latex table code.
%
%   'latexCode'  - table latex code, generated by convert_LMM2latexTable
%   'oldName'    -  cell array containing the strings to be replaced
%   'newName'    -  cell array containing the new strings. The dimension
%                   and order should match 'oldName'

%   Written by Pierre Petitet (pierre.petitet@gmail.com)
%   Last update: 24/11/2019

for v = 1:length(oldName)
    idx = find(contains(latexCode,oldName{v}));
    if ~isempty(idx)
        for i = 1:length(idx)
            if contains(latexCode{idx(i),1},'\label') 
                continue;
            end
            latexCode{idx(i),1}=strrep(latexCode{idx(i),1},oldName{v},newName{v});            
        end
    end
end
end